<?php
namespace AGTI\Bling\Infrastructure\Service\Api\Bling\Orders\CreateOrder;

use AGTI\Bling\Infrastructure\Service\Api\Bling\BaseService;
use AGTI\Bling\Infrastructure\Service\Api\Bling\DataModels\Order;

class CreateOrderService extends BaseService
{
    public function getApiEndpoint()
    {
        return "pedidos/vendas";
    }

    /**
     * @return CreateOrderResponseSuccess|null
     */
    public function exec(Order $order)
    {
        // numero is generated by Bling. numeroLoja carries the local order
        // number and must not be reused as the internal Bling number.
        $body = json_decode($this->getSerializer()->serialize($order, 'json'), true);
        unset($body['numero']);

        $r = $this->send(
            "POST",
            [],
            json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
        );

        if ($r->getHttpCode() == 201) {
            return $this->getSerializer()->deserialize($this->getRequest()->getResponse(), CreateOrderResponseSuccess::class, 'json');
        }
    }
}
